name = "MRCS"
uuid = "0388ec21-aa36-4466-b1eb-2f71ac59f0e4"
authors = ["Mohammad Azarbad"]
version = "1.0.0-DEV"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"

[compat]
IJulia = "1.25.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
